title: Nikos Sofias
author: Nikos Sofias
description: >-
  Welcome to my professional portfolio. I'm a [your profession] based in [location].

remote_theme: "jekyll/minima@1e8a445"

# Optional extras:
email: your.email@example.com
github_username: nikossofias
linkedin_username: your-linkedin
